#Original script provided by Thomas Feher and subsequently adapted.
#if you want to work on this, please talk with us on
# https://lists.sourceforge.net/lists/listinfo/audacity-devel
#build time is circa 7 mins.
version: 2.4.1-alpha-{build}
image: Visual Studio 2017
shallow_clone: true # reduce traffic
install:
    - 'echo #define REV_LONG "%APPVEYOR_REPO_COMMIT%" > src\RevisionIdent.h'
    - 'echo #define REV_TIME "%APPVEYOR_REPO_COMMIT_TIMESTAMP%" >> src\RevisionIdent.h'
    # install gettext tool (only used by target "locale", which is not built at
    # the moment due to long duration
    - nuget install Gettext.Tools -Version 0.19.8.1 -OutputDirectory %AUDACITY_ROOT%\win\packages
    # download wxWidgets
    - git clone --recurse-submodules --branch v3.1.1 --depth 1 --jobs 4 https://github.com/audacity/wxWidgets.git %WXWIN%
    # build wxWidgets
    - msbuild /m %WXWIN%\build\msw\wx_vc15.sln "/p:Configuration=DLL Release;Platform=Win32;PlatformToolset=v141" /target:adv,base,core,html,net,qa,wxexpat,wxjpeg,wxpng,wxtiff,wxzlib,xml /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
environment:
    WXWIN: '%APPVEYOR_BUILD_FOLDER%\lib-src\wxWidgets'
    AUDACITY_ROOT: '%APPVEYOR_BUILD_FOLDER%'
# replace `build_script` with `build` and `configuration` when complete build
# does not exceed a duration of 1 hour
#build:
    #project: win/audacity.sln
#configuration:
    #- Release
build_script: # build all targets except `help`
- cmd: >-
    msbuild /m win/audacity.sln /p:Configuration=Release;Platform=Win32;PlatformToolset=v141 /target:expat,filedialog,libflac++,libflac,libid3tag,libmad,libnyquist,libogg,libscorealign,libsndfile,libsoxr,libvamp,libvorbis,lv2,portaudio-v19,portmidi,portmixer,portsmf,sbsms,soundtouch,twolame,Audacity /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" &&
    del /S win\Release\*.ipdb &&
    del /S win\Release\*.iobj &&
    del /S win\Release\*.lib &&
    del /S win\Release\*.pdb &&
    del /S win\Release\*.exp &&
    copy %WXWIN%\lib\vc_dll\*.dll win\Release\
artifacts:
- path: win\Release
  name: 'audacity-%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%'

