name: '[AU4] Check: Codestyle'

on:
  pull_request:
  workflow_dispatch:

jobs:
  au4_codestyle:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - name: Fetch Muse CI scripts
      run: |
        cmake -P ./buildscripts/ci/checkcodestyle/ci_fetch.cmake

    - name: Test coding style
      run: |
        cmake -P ./buildscripts/ci/checkcodestyle/_deps/checkcodestyle.cmake ./src/
