name: CMake Build

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      AUDACITY_CMAKE_GENERATOR: ${{ matrix.config.generator }}
      CMAKE_ARCH_LABEL: ${{ matrix.config.cmake-arch }}
      CONAN_ARCH_LABEL: ${{ matrix.config.conan-arch }}
      # Windows codesigning
      # This variables will be used by all the steps
      WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
      WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
      # Conan home location to be used for cache action
      CONAN_USER_HOME: "${{ github.workspace }}/conan-home/"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-home/short"
    strategy:
      fail-fast: false
      matrix:
        config:

        - name: Ubuntu_18.04
          os: ubuntu-18.04
          cmake-arch: ""
          conan-arch: x86_64
          generator: Unix Makefiles

        - name: macOS
          os: macos-latest
          cmake-arch: ""
          conan-arch: x86_64
          generator: Xcode

        - name: Windows_x86
          os: windows-latest
          cmake-arch: Win32
          conan-arch: x86
          generator: Visual Studio 16 2019

        - name: Windows_x86_64
          os: windows-latest
          cmake-arch: x64
          conan-arch: x86_64
          generator: Visual Studio 16 2019

        - name: Windows_armv8
          os: windows-latest
          cmake-arch: ARM64
          conan-arch: armv8
          generator: Visual Studio 16 2019

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Dependencies
      run: |
        exec bash "scripts/ci/dependencies.sh"

    - name: Environment
      run: |
        source "scripts/ci/environment.sh"
    
    - name: Install Apple codesigning certificates
      uses: apple-actions/import-codesign-certs@v1
      if: startswith( matrix.config.os, 'macos' ) && github.event_name == 'push' && github.repository_owner == 'audacity'
      with: 
        p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
        p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

    - name: Cache for .conan
      id: cache-conan
      uses: actions/cache@v2
      env:
        cache-name: cache-conan-modules
      with:
        path: ${{ env.CONAN_USER_HOME }}
        key: host-${{ matrix.config.name }}-${{ hashFiles('cmake-proxies/CMakeLists.txt') }}
        restore-keys: |
          host-${{ matrix.config.name }}-

    - name: Configure
      env:
        # Error reporing
        SENTRY_DSN_KEY: ${{ secrets.SENTRY_DSN_KEY }}
        SENTRY_HOST: ${{ secrets.SENTRY_HOST }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        CRASH_REPORT_URL: ${{ secrets.CRASH_REPORT_URL }}
        # Apple code signing
        APPLE_CODESIGN_IDENTITY: ${{ secrets.APPLE_CODESIGN_IDENTITY }}
        APPLE_NOTARIZATION_USER_NAME: ${{ secrets.APPLE_NOTARIZATION_USER_NAME }}
        APPLE_NOTARIZATION_PASSWORD: ${{ secrets.APPLE_NOTARIZATION_PASSWORD }}
      run: |
        exec bash "scripts/ci/configure.sh"

    - name: Build
      run: |
        exec bash "scripts/ci/build.sh"

    - name: Upload debug symbols
      if: startsWith(github.ref, 'refs/heads/release-')
      env:
        SENTRY_HOST: ${{ secrets.SENTRY_HOST }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
        SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG }}
        #this is required to run sentry's get-cli script on platforms where 'sudo' is not available
        INSTALL_DIR: ${{ github.workspace }}
      run: |
        exec bash "scripts/ci/upload_debug_symbols.sh"

    - name: Install
      run: |
        exec bash "scripts/ci/install.sh"

    - name: Package
      run: |
        exec bash "scripts/ci/package.sh"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Audacity_${{ matrix.config.name }}_${{ github.run_id }}_${{ env.GIT_HASH_SHORT }}
        path: |
          build/package/*
          !build/package/_CPack_Packages
        if-no-files-found: error
